# Generated by Django 2.2.5 on 2019-10-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm.TimestampedModel')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            bases=('farm.timestampedmodel',),
        ),
    ]
