# Generated by Django 2.2.5 on 2019-10-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='name',
            new_name='role_name',
        ),
    ]
