# Generated by Django 2.2.5 on 2019-10-01 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_auto_20191001_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorker',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm.TimestampedModel')),
                ('user_name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=60, null=True)),
            ],
            bases=('farm.timestampedmodel',),
        ),
    ]
