# Generated by Django 2.2.5 on 2019-10-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_fieldworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerGroup',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm.TimestampedModel')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('farmer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='farm.FarmerGroup')),
            ],
            bases=('farm.timestampedmodel',),
        ),
    ]
