# Generated by Django 2.2.5 on 2019-10-01 09:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_farmergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm.TimestampedModel')),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(max_length=60)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone number')),
            ],
            bases=('farm.timestampedmodel',),
        ),
    ]
