# Generated by Django 2.2.5 on 2019-10-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmuser',
            name='via_search',
            field=models.BooleanField(default=False),
        ),
    ]
